apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  labels:
    self-node-remediation-operator: ""
  name: selfnoderemediations.self-node-remediation.medik8s.io
spec:
  group: self-node-remediation.medik8s.io
  names:
    kind: SelfNodeRemediation
    listKind: SelfNodeRemediationList
    plural: selfnoderemediations
    shortNames:
    - snr
    - snremediation
    singular: selfnoderemediation
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SelfNodeRemediation is the Schema for the selfnoderemediations
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SelfNodeRemediationSpec defines the desired state of SelfNodeRemediation
            properties:
              remediationStrategy:
                default: ResourceDeletion
                description: RemediationStrategy is the remediation method for unhealthy
                  nodes currently "NodeDeletion" is deprecated and "ResourceDeletion"
                  will always happen, regardless of which strategy is selected it
                  will iterate over all pods and volume attachments related to the
                  unhealthy node and delete them
                enum:
                - ResourceDeletion
                - NodeDeletion
                type: string
            type: object
          status:
            description: SelfNodeRemediationStatus defines the observed state of SelfNodeRemediation
            properties:
              lastError:
                description: LastError captures the last error that occurred during
                  remediation. If no error occurred it would be empty
                type: string
              phase:
                description: 'Phase represents the current phase of remediation, One
                  of: TBD'
                type: string
              timeAssumedRebooted:
                description: TimeAssumedRebooted is the time by then the unhealthy
                  node assumed to be rebooted
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
